services:
  postgres:
    image: postgres:15-alpine
    container_name: personal_finance_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: personal_finance_local
    ports:
      - "6543:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
